on:
  create:
    tags:
    - v*.*.*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run:  zip -r -X "./gcp-console.alfredworkflow" . -x ".github" -x ".git" -x "Makefile" -x "items.csv"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gcp-console.alfredworkflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
